qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_01_0_13.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_01_13_27.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_01_27_41.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_01_41_55.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_01_55_69.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_01_69_83.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_01_83_97.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_01_97_111.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_01_111_125.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_01_125_139.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_01_139_153.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_01_153_167.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_01_167_181.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_01_181_195.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_01_195_209.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_01_209_223.sh
