qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_01_0_8.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_01_8_17.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_01_17_26.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_01_26_35.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_01_35_44.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_01_44_52.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_01_52_61.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_01_61_70.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_01_70_79.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_01_79_88.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_01_88_96.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_01_96_105.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_01_105_114.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_01_114_123.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_01_123_132.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_01_132_141.sh
