qsub /home/samdixon/host_unity/scripts/mcmc_ps_0_14.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_14_28.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_28_42.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_42_56.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_56_70.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_70_84.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_84_98.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_98_112.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_112_126.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_126_140.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_140_154.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_154_168.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_168_182.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_182_196.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_196_210.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_210_225.sh
