qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_03_0_13.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_03_13_27.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_03_27_41.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_03_41_55.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_03_55_69.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_03_69_83.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_03_83_97.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_03_97_111.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_03_111_125.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_03_125_139.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_03_139_153.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_03_153_167.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_03_167_181.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_03_181_195.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_03_195_209.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_03_209_223.sh
