qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_02_0_13.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_02_13_27.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_02_27_41.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_02_41_55.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_02_55_69.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_02_69_83.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_02_83_97.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_02_97_111.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_02_111_125.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_02_125_139.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_02_139_153.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_02_153_167.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_02_167_181.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_02_181_195.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_02_195_209.sh
qsub /home/samdixon/host_unity/scripts/mcmc_ps_error_floor_02_209_223.sh
