qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_02_0_8.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_02_8_17.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_02_17_26.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_02_26_35.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_02_35_44.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_02_44_52.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_02_52_61.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_02_61_70.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_02_70_79.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_02_79_88.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_02_88_96.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_02_96_105.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_02_105_114.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_02_114_123.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_02_123_132.sh
qsub /home/samdixon/host_unity/scripts/mcmc_csp_err_floor_02_132_141.sh
